### ISSUE TITLE
Error Code: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by enzanki-ars** [geooot/gradedapp#3]
When attempting to login to my school's Home Access Center, this error appears.  If you need more info, let me know.

**Comment by geooot** [comment]
Please let me know of your school district. I also made a recent change that might make it work now. Thank you for reporting a bug! I'll get on it

**Comment by enzanki-ars** [comment]
I can now sign in, but I am seeing the placeholder text on all graded pages.  
(I would love to assist you in the development of this app, but it seems only the source of your website is accessible online...)
![image](https://cloud.githubusercontent.com/assets/8580211/10711259/8bb083e6-7a43-11e5-9b64-fa0f16e0468e.png)

**Comment by enzanki-ars** [comment]
By the way, my school is the Hilliard City School District in Hilliard, Ohio.  I do not know if this will help you as not much information is accessible without logging in.  If the code for the app was accessible online, I would be willing to debug and pinpoint/correct the issue.

**Comment by geooot** [comment]
It seems the problem lies between the server trying to scrape you current class work. can you send me a screenshot of the you school districts actual site HAC site on the classwork page? It might be in a different format than my districts, causing the error.

![hac](https://cloud.githubusercontent.com/assets/7832610/10711309/9a3eb22c-7a3c-11e5-8b84-c49366125ae1.PNG)

Another thing. Does your classes names show up on the previous "Classwork" on the app?
![scr](https://cloud.githubusercontent.com/assets/7832610/10711321/f81748aa-7a3c-11e5-8c98-c7ca3f005345.PNG)

**Comment by enzanki-ars** [comment]
My class names appear correctly, but not the grades.  Email me at shafer.alex@gmail.com and I will send you a picture of our HAC page.  I would like to keep my current grades private.

**Comment by geooot** [comment]
alright sent you an email!
